---
- name: Initialize SSH and WWW
  hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - ocp4install

- name: Setup WWW
  hosts: www
  gather_facts: yes
  become: yes
  tasks:
  - name: Setup HTTP
    include_role:
      name: ocp4install
      tasks_from: setuphttp

