---
# Create SSH Key for installation
- include_vars:
    file: redhat-secrets.yml

- debug:
    var: ocp4_sshkey

- name: Create Installation Base Directory
  file:
    state: directory
    path: "{{ base }}"

- name: "Create installation directory {{ clustername }}"
  file:
    state: directory
    path: "{{ base }}/{{ clustername }}"
  register: instbase

- name: Create install-config
  template:
    src: install-config.j2
    dest: "{{ instbase.path }}/install-config.yaml"

- name: Backup install-config
  copy:
    src: "{{ instbase.path }}/install-config.yaml"
    dest: "{{ instbase.path }}/backup-install-config.yaml"

- name: Create manifests
  shell: "~/bin/openshift-install create manifests --dir={{ instbase.path }}"
  register: inst_manifest 

- name: Add cluster-network-03-config file
  template:
    src: cluster-network-03-config.j2
    dest: "{{ instbase.path }}/manifests/cluster-network-03-config.yml"

- name: Create ignition files
  shell: "openshift-install create ignition-configs --dir={{ instbase.path }}"
  register: inst_ignition

